### ISSUE TITLE
when used with paperpile bibliography citations form diagonal

### ISSUE THREAD

**Issue by arw36** [PabiGamito/gdocs-line-numbering-chrome-extension#13]
Line numbers begin to cut across page, intersecting the bibliography, and wrap in a diagonal.

**Comment by PabiGamito** [comment]
Would you be able to post a screenshot of this behavior?

**Comment by PabiGamito** [comment]
Might this be related to this merge request: https://github.com/PabiGamito/gdocs-line-numbering-chrome-extension/pull/7

**Comment by arw36** [comment]
![screen shot 2018-12-10 at 3 46 11 pm](https://user-images.githubusercontent.com/16709317/49760573-c8dab000-fc92-11e8-8a73-ff285212fe7f.png)

**Comment by arw36** [comment]
Alternatively, could add a stop numbering lines after X condition?

**Comment by fjparada** [comment]
Using same Paperpile+LineNumbers combo on Mac OSX 10.13 and references section looks good. I have the same problem with footnotes.

![screen shot 2019-02-07 at 4 20 34 pm](https://user-images.githubusercontent.com/14896072/52436929-55b7b380-2af4-11e9-8960-14ff693cc7e4.png)
![screen shot 2019-02-07 at 4 20 03 pm](https://user-images.githubusercontent.com/14896072/52436934-5a7c6780-2af4-11e9-902e-c64b2007c1ad.png)

**Comment by PabiGamito** [comment]
Hopefully, https://github.com/PabiGamito/gdocs-line-numbering-chrome-extension/issues/20 should have fixed the problems with footnotes. Could you double check if the problem is still persistent using the latest version of the extension with paperpile?

**Comment by arw36** [comment]
Seems the paperpile citations overlap issue is fixed. I am seeing some issues with indented paragraphs/outlines
![Screen Shot 2019-03-26 at 8 13 59 PM](https://user-images.githubusercontent.com/16709317/55041525-d3337680-5003-11e9-9081-7946e35a49f1.png)
![Screen Shot 2019-03-26 at 8 13 11 PM](https://user-images.githubusercontent.com/16709317/55041526-d3337680-5003-11e9-87b0-4c80aad9399a.png)

**Comment by PabiGamito** [comment]
Thanks for getting back with an update so quickly!

That's great to hear.

I will look into the indentation issue and hopefully publish a fix very soon. I've created an issue for it: #23

**Comment by PabiGamito** [comment]
@arw36 Can you confirm this is no longer an issue in the latest version of the extension?

For now, I will assume this issue is fixed as I can't seem to reproduce it.
