### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by mvosburgh** [PabiGamito/gdocs-line-numbering-chrome-extension#14]
Your extension worked as of 1/27/2019.  However as of today, when enabled, no line numbers appear on Google Docs.  Nothing happens when the extension is enabled.

**Comment by PabiGamito** [comment]
May I ask what version of Chrome are you using as the extension still works for me on version 72.0.3626.81. What OS are you using?

**Comment by mvosburgh** [comment]
Good morning,

Thanks for reaching out.

I work on a Samsung Chromebook Pro and I am running Chrome OS (Version 71.0.3578.127).

Thanks,

Matt V

________________________________

**Comment by fjparada** [comment]
Is working great on Mac OSX 10.13

**Comment by mvosburgh** [comment]
I have not tried it on another device.  All I know is that it was working as of a week and a half ago, but now is not.  I tried uninstalling and reinstalling the app as well.  Am I doing something wrong? Screenshot attached with what I am seeing.
________________________________

**Comment by mvosburgh** [comment]
As of this morning, it is working again.

Thanks for your time!

Matt V
________________________________

**Comment by PabiGamito** [comment]
Since it seems to be working I will close this issue.

If it ever break again, feel free to post here again for me to take a look at this again.
