### ISSUE TITLE
Missing per Document Settings

### ISSUE THREAD

**Issue by PabiGamito** [PabiGamito/gdocs-line-numbering-chrome-extension#3]
Make is so the user can enable and disable line numbering and set every how many lines should be numbered per document and remember it next time the same document is loaded.

**Comment by jmason888-berkeley** [comment]
Even better, if this could be a Docs add-on rather than a Chrome extension....

**Comment by PabiGamito** [comment]
That's what I initially wanted to do, but it turns out there was no obvious way to make it as a docs add-on when I created this extension.

I might take a look at the possibilities of turning this into a google docs add-on.

**Comment by PabiGamito** [comment]
As of v2.0.0 of the extension line numbering settings are per document.
