### ISSUE TITLE
Improperly numbers tables

### ISSUE THREAD

**Issue by michaelboss** [PabiGamito/gdocs-line-numbering-chrome-extension#5]
AddOn is doing something strange with tables, where they get a lot of line numbers associated with them.  This makes line numbers in Docs not match closely with MS Word.

**Comment by PabiGamito** [comment]
Would you be able to provide an example document where this happens? Please share a public link to the document so I may check it out.

**Comment by michaelboss** [comment]
https://docs.google.com/document/d/13gpYBPNSlhlfzSWF4MGoVvqfTSD0jTsJ9ZyRSqNifLI/edit?usp=sharing

Here are my options:


​

Thanks for the quick reply, let me know what you think.

-Michael

**Comment by PabiGamito** [comment]
Fixed in latest commit. Uploading to chrome store. Changes should take place soon.
